services:
  nginx:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: ./
      dockerfile: Dockerfile_PHP
    container_name: php
    volumes:
      - ./src:/var/www/public
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword

volumes:
  db_data:
