services:
  nginx:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/public
      - ./config/default.conf:/etc/nginx/conf.d/default.conf 
    depends_on:
      - php

  php:
    build:
      context: ./
      dockerfile: dockerfile-php
    container_name: php
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - ./db/userInit.sql:/docker-entrypoint-initdb.d/initfile.sql
    expose:
      - "3306"

volumes:
  db_data:
