# Use the official PHP image as the base image
FROM php:8.2-fpm


WORKDIR /var/www/public

RUN apt-get update && apt-get install -y \
    mariadb-client \
    libmariadb-dev \
    libzip-dev \
    unzip \
    && docker-php-ext-install \
    mysqli \
    pdo_mysql \
    zip \
    && apt-get clean && rm -rf /var/lib/apt/lists/* 

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy custom PHP configuration file
COPY ./config/php.ini /usr/local/etc/php/conf.d/custom.ini

# Copy application files
COPY app /var/www/app
COPY config /var/www/config
COPY routes /var/www/routes
COPY public /var/www/public
COPY views /var/www/views

COPY composer.json /var/www/composer.json

WORKDIR /var/www

RUN composer install 
RUN composer require symfony/routing
RUN composer require symfony/http-foundation

WORKDIR /var/www/public

EXPOSE 9000

CMD ["php-fpm"]
