# Use the official PHP image as the base image
FROM php:8.2-fpm

WORKDIR /var/www/public

COPY ./config/php.ini /usr/local/etc/php/conf.d/custom.ini
COPY ./mock-public /var/www/public

RUN sed -i 's/9000/9001/g' /usr/local/etc/php-fpm.d/www.conf
RUN sed -i 's/9000/9001/g' /usr/local/etc/php-fpm.d/zz-docker.conf

EXPOSE 9001

CMD ["php-fpm"]
