# Use the official PHP image as the base image
FROM php:8.2-fpm

# Install required dependencies for MariaDB and PHP extensions
RUN apt-get update && apt-get install -y \
    mariadb-client \
    libmariadb-dev \
    libzip-dev \
    unzip \
    && docker-php-ext-install \
    mysqli \
    pdo_mysql \
    zip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*



# COPY ./public /var/www/public
# COPY ./app /var/www/public/app
# COPY ./core /var/www/public/core

WORKDIR /var/www/public

# Expose the default PHP-FPM port
EXPOSE 9000

# Start PHP-FPM server
CMD ["php-fpm"]
